plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/growthgene/그로스진 마케팅/landings/prysm-conference"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]